name: Rotate Repo Keys

on:
  push:
  workflow_dispatch:
    environment:
        description: 'Environment to run tests against'
        type: environment
        default: 'dev'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  # https://www.gnupg.org/documentation/manuals/gnupg/Unattended-GPG-key-generation.html
  generate-key:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'dev' }}
    steps:
      - uses: step-security/harden-runner@v2
        with:
            egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      # $() must be in "double quotations" or else it won't process first
      - name: Generate temp directory for gnupg
        run: echo "GNUPGHOME=$(mktemp -d)" >> "$GITHUB_ENV"
      - run: |
          cat >foo <<EOF
            %echo Generating a basic OpenPGP key
            Key-Type: DSA
            Key-Length: 1024
            Subkey-Type: ELG-E
            Subkey-Length: 1024
            Name-Real: Joe Tester
            Name-Comment: with stupid passphrase
            Name-Email: ${{ github.repository_owner_id }}+${{ github.repository_owner }}@users.noreply.github.com
            Expire-Date: 0
            Passphrase: ${{ secrets.GNUPG_KEY_PASSPHRASE }}
            # Do a commit here, so that we can later print "done" :-)
            %commit
            %echo done
          EOF
      - run: gpg --batch --full-gen-key foo
      - run: gpg --list-secret-keys