name: Update release files

on:
  push:
    paths:
      - '.github/workflows/releaseFiles.yml'
      - 'apt/**'
  workflow_dispatch:
    inputs:
      environment:
          description: 'Environment to run tests against'
          type: environment
          default: 'dev'
          required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  generate-packages:
    runs-on: ubuntu-latest
    # environment: ${{ inputs.environment || 'prod' }}
    environment: ${{ inputs.environment || 'dev' }}
    permissions:
      contents: write
    steps:
      - uses: step-security/harden-runner@v2
        with:
            egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@v3
      - run: git config user.name "repo[bot]"
      # Package index files
      - name: Create index file
        run: dpkg-scanpackages --multiversion . > Packages
        working-directory: apt
      - name: Create compressed index file
        run: gzip -k -f Packages
        working-directory: apt
      - run: git commit -m 'Updated packages index' 'Packages' 'Packages.gz'
        working-directory: apt
      # Release index files
      - name: Create index file
        run: apt-ftparchive release . > Release
        working-directory: apt

      - run: echo -e "${{ secrets.GNUPG_KEY_PRIVATE }}" > gpg-private-key.asc
      # $() must be in "double quotations" or else it won't process first
      - name: Generate temp directory for gnupg
        run: echo "GNUPGHOME=$(mktemp -d)" >> "$GITHUB_ENV"
      - name: Import GPG
        run: gpg --batch --no-tty --pinentry-mode=loopback --passphrase "${{ secrets.GNUPG_KEY_PASSPHRASE }}" --import gpg-private-key.asc
      - name: Sign Release
      - run: gpg --default-key "${{ github.repository_owner_id }}+${{ github.repository_owner }}@users.noreply.github.com" -abs -o Release.gpg Release
      - run: gpg --default-key "${{ github.repository_owner_id }}+${{ github.repository_owner }}@users.noreply.github.com" --clearsign -o InRelease Release

      - run: git add 'Release.gpg' 'InRelease'
      - run: git commit -m 'Updated releases index' 'Release' 'Release.gpg' 'InRelease'
        working-directory: apt
      - run: git status

      - run: git push