name: Update release files

on:
  push:
    paths:
      - '.github/workflows/releaseFiles.yml'
      - 'apt/**'
  workflow_dispatch:
    environment:
        description: 'Environment to run tests against'
        type: environment
        default: 'dev'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

# defaults:
#   run:
#     working-directory: apt

jobs:
  generate-packages:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'prod' }}
    permissions:
      contents: write
    steps:
      - uses: step-security/harden-runner@v2
        with:
            egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@v3
      - name: Create index file
        run: dpkg-scanpackages --multiversion . > Packages
        working-directory: apt
      - name: Create compressed index file
        run: gzip -k -f Packages
        working-directory: apt
      - run: git config user.name "repo[bot]"
      - run: tree -a -pughF
      - run: git commit -m 'Updated index files' 'apt/Packages' 'apt/Packages.gz'
      - run: git push
  generate-releases:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'prod' }}
    permissions:
      contents: write
    steps:
      - uses: step-security/harden-runner@v2
        with:
            egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@v3
      - name: Create index file
        run: apt-ftparchive release . > Release
        working-directory: apt
      - run: tree -a -pughF
      - run: git config user.name "repo[bot]"
      - run: git status
      - run: git commit -m 'Updated signing key' 'apt/Release'
      - run: git push