name: Update release files

on:
  push:
    paths:
      - '.github/workflows/releaseFiles.yml'
      - 'apt/**'
  workflow_dispatch:
    environment:
        description: 'Environment to run tests against'
        type: environment
        default: 'dev'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  generate-packages:
    runs-on: ubuntu-latest
    # environment: ${{ inputs.environment || 'prod' }}
    environment: ${{ inputs.environment || 'dev' }}
    permissions:
      contents: write
    steps:
      - uses: step-security/harden-runner@v2
        with:
            egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@v3
      - run: git config user.name "repo[bot]"
      # Package index files
      - name: Create index file
        run: dpkg-scanpackages --multiversion . > Packages
        working-directory: apt
      - name: Create compressed index file
        run: gzip -k -f Packages
        working-directory: apt
      - run: git commit -m 'Updated packages index' 'Packages' 'Packages.gz'
        working-directory: apt
      # Release index files
      - name: Create index file
        run: apt-ftparchive release . > Release
        working-directory: apt

      - run: echo -e "$GPG_KEY" > PRIVATE_GPG_KEY.asc
      - name: Import GPG
        run: gpg --batch --pinentry-mode=loopback --passphrase "${{ secrets.GNUPG_KEY_PASSPHRASE }}" --dearmor import PRIVATE_GPG_KEY.asc
      - run: gpg --list-secret-keys

      - run: tree -a -pughF
        if: ${{ failure() }}
      - run: git commit -m 'Updated releases index' 'Release'
        working-directory: apt
      - run: git status

      - run: git push