name: synthetic-monitoring-agent update checker

on:
  push:
    paths:
      - '.github/workflows/syntheticMonitoringAgentChecker.yml'
  schedule:
    # https://crontab.guru/every-year
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      environment:
          description: 'Environment to run in'
          type: environment
          default: 'dev'
          required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  latest-version-tag:
    runs-on: ubuntu-latest
    # environment: ${{ inputs.environment || 'prod' }}
    environment: ${{ inputs.environment || 'dev' }}
    permissions:
      contents: write
    steps:
      - uses: step-security/harden-runner@v2
        with:
            egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@v3
      - run: gh release list --exclude-drafts -L 1 -R grafana/synthetic-monitoring-agent > synthetic-monitoring-agent.temp
        working-directory: lastupdate
        env:
          GH_TOKEN: ${{ github.token }}
        working-directory: lastupdate

      - run: git config user.name "repo[bot]"
      - run: git commit -m 'New synthetic-monitoring-agent version' 'synthetic-monitoring-agent.latest'
        working-directory: lastupdate
      - run: git push

      - name: TEMP
        uses: actions/github-script@v6
        with:
          script: core.setFailed('TODO')