name: synthetic-monitoring-agent update checker

on:
  push:
    paths:
      - '.github/workflows/syntheticMonitoringAgentChecker.yml'
  schedule:
    # https://crontab.guru/every-year
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      environment:
          description: 'Environment to run in'
          type: environment
          default: 'dev'
          required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  synthetic-monitoring-agent-latest-version-tag:
    runs-on: ubuntu-latest
    # environment: ${{ inputs.environment || 'prod' }}
    environment: ${{ inputs.environment || 'dev' }}
    steps:
      - uses: step-security/harden-runner@v2
        with:
            egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - run: gh release list -R grafana/synthetic-monitoring-agent
      - name: TEMP
        uses: actions/github-script@v6
        with:
          script: core.setFailed('TODO')