name: synthetic-monitoring-agent update checker

on:
  push:
    paths:
      - '.github/workflows/syntheticMonitoringAgentChecker.yml'
  schedule:
    # https://crontab.guru/every-year
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      environment:
          description: 'Environment to run in'
          type: environment
          default: 'dev'
          required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  latest-version-tag:
    runs-on: ubuntu-latest
    # environment: ${{ inputs.environment || 'prod' }}
    environment: ${{ inputs.environment || 'dev' }}
    permissions:
      contents: write
    steps:
      - uses: step-security/harden-runner@v2
        with:
            egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@v3
      
      - name: Get latest version
        run: gh release list -R grafana/synthetic-monitoring-agent --exclude-drafts -L 1 > synthetic-monitoring-agent.temp
        working-directory: lastupdate
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Check latest version vs last checked version
        run: '! diff synthetic-monitoring-agent.temp synthetic-monitoring-agent.latest'
        working-directory: lastupdate
      - run: mkdir -p apt/pool/main/synthetic-monitoring-agent
      - name: Download latest version
        run: gh release download -R grafana/synthetic-monitoring-agent -p '_*linux_arm*.deb' -D 'apt/pool/main/synthetic-monitoring-agent'
      - run: gh release download -R grafana/synthetic-monitoring-agent -p 'checksums.txt' -O - | sha256sum -c - *
        working-directory: apt/pool/main/synthetic-monitoring-agent

      - run: git config user.name "repo[bot]"
      - run: git commit -m 'New synthetic-monitoring-agent version' 'synthetic-monitoring-agent.latest'
        working-directory: lastupdate
      - run: git push

      - name: TEMP
        uses: actions/github-script@v6
        with:
          script: core.setFailed('TODO')