name: synthetic-monitoring-agent update checker

on:
  push:
    paths:
      - '.github/workflows/syntheticMonitoringAgentChecker.yml'
  schedule:
    # https://crontab.guru/every-year
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      environment:
          description: 'Environment to run in'
          type: environment
          default: 'dev'
          required: true