name: synthetic-monitoring-agent update checker

on:
  push:
    paths:
      - '.github/workflows/syntheticMonitoringAgentChecker.yml'
  schedule:
    # https://crontab.guru/every-year
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      environment:
          description: 'Environment to run in'
          type: environment
          default: 'dev'
          required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  latest-version-tag:
    runs-on: ubuntu-latest
    # environment: ${{ inputs.environment || 'prod' }}
    environment: ${{ inputs.environment || 'dev' }}
    steps:
      - uses: step-security/harden-runner@v2
        with:
            egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      # sed s/insert regex here/backslash group # from regex/p
      - run: gh release list --exclude-drafts -L 1 -R grafana/synthetic-monitoring-agent | echo $(sed -nr 's/^v(\d+\.\d+\.\d+)\s.+$/\1/p')
        env:
          GH_TOKEN: ${{ github.token }}
      - name: TEMP
        uses: actions/github-script@v6
        with:
          script: core.setFailed('TODO')